title: <p align="center"> Srinivasan Ramanujam </p>
logo: /assets/img/logo.jfif
description:
  <p align="center">
  <a href="https://www.linkedin.com/in/ramanujamthearchitect">LinkedIn</a> |
  <a href="https://github.com/srinirama">GitHub</a>
  </p>
  <h2>
  Vice President - Standard Chartered Bank (Global Business Services)
  </h2> 
  
show_downloads: False
theme: jekyll-theme-minimal
