title: <p align="center"> Srinivasan Ramanujam </p>
logo: /assets/img/logo.jfif

description:
  <p align="center">

  <a href="https://www.linkedin.com/in/ramanujamthearchitect//">LinkedIn</a> |
  <a href="https://github.com/srinirama">GitHub</a>
 
  <br>  
  Vice President - Standard Chartered Bank (Global Business Services)
  </br>
  </p>



theme: jekyll-theme-minimal
