title: <p align="center"> Srinivasan Ramanujam </p>
logo: /assets/img/logo.jfif
description:
  <p align="center">
  <a href="https://www.linkedin.com/in/ramanujamthearchitect">LinkedIn</a> |
  <a href="https://github.com/srinirama">GitHub</a>
  </p>
  
  
show_downloads: false
theme: jekyll-theme-minimal
